#include "keyboard.h"
#include "lib.h"
#include "i8259.h"

//flags of modifier keys
uint8_t caps  = 0;
uint8_t ctrl  = 0;
uint8_t shrf = 0;
uint8_t numl  = 0;

//scan code table1
//If there is no correspoding ascii code in the scan code set, output '\0'
char scan_code_table[SCAN_CODE_PRESS] = {
	'\0', '\0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
	'-', '=', '\b', '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 
	'o', 'p', '[', ']', '\n', '\0', 'a', 's', 'd', 'f', 'g', 'h', 
	'j', 'k', 'l' , ';', '\'', '`', '\0', '\\', 'z', 'x', 'c', 'v', 
	'b', 'n', 'm', ',', '.', '/', '\0', '\0', '\0', ' ', '\0',
};

/* The table to translate scan code to ASCII code when caps is pressed */
char scan_code_table_caps[SCAN_CODE_PRESS] = {
	'\0', '\0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=',
	'\b', '\t', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
	'[', ']', '\n', '\0',
	'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L' ,
	';', '\'', '`', '\0', '\\',
	'Z', 'X', 'C', 'V', 'B', 'N', 'M',
	',', '.', '/', '\0', '\0', '\0', ' ', '\0',
};

/* The table to translate scan code to ASCII code when shift is pressed */
char scan_code_table_shift[SCAN_CODE_PRESS] = {
	'\0', '\0', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+',
	'\b', '\t', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
	'{', '}', '\n', '\0',
	'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L' ,
	':', '\"', '~', '\0', '|',
	'Z', 'X', 'C', 'V', 'B', 'N', 'M',
	'<', '>', '?', '\0', '\0', '\0', ' ', '\0',
};

/* The table to translate scan code to ASCII code when shift and caps are pressed */
char scan_code_table_shift_caps[SCAN_CODE_PRESS] = {
	'\0', '\0', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+',
	'\b', '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p',
	'{', '}', '\n', '\0',
	'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l' ,
	':', '\"', '~', '\0', '|',
	'z', 'x', 'c', 'v', 'b', 'n', 'm',
	'<', '>', '?', '\0', '\0', '\0', ' ', '\0',
};

char scan_code_table_keypad[KEYPAD_NUM]={
	'7', '8', '9', '-', '4', '5', '6', '+', '1', '2', '3', '0', '.'
};

/*
*   key_init
*   initialize the keyboard's irq on PIC
*   input: None
*   output: None
*   side effect: PIC's IRQ1 is enabled. 
*/
void key_init(void) {
	/* The keyboard is connected to IR1 on the PIC */
	enable_irq(KEY_IRQ_NUM);
}


/*
*   key_handler
*   manage interrupt generated by keyboard
*   input: None
*   output: None
*   side effect: print the value of the pressed key on screen
*/
void key_handler(void) {
	cli();
	uint8_t scan_code, ascii;

	//get scan code from port
    //the size of scan code is one byte
	scan_code = inb(KEY_BUF_PORT);
	
	/* Handle modifier keys */
	switch (scan_code) {
		case LEFT_CTRL_PRESSED:		ctrl = 1;		break;
		case LEFT_CTRL_RELEASED:	ctrl = 0;		break;
		case LEFT_SHIFT_PRESSED:	shrf = 1;		break;
		case LEFT_SHIFT_RELEASED:	shrf = 0;		break;
		case RIGHT_SHIFT_PRESSED:	shrf = 1;		break;
		case RIGHT_SHIFT_RELEASED:	shrf = 0;		break;
		case CAPS_LOCK_PRESSED:		caps = !caps;	break;
		case NUM_LOCK_PRESSED:		numl = !numl;	break;

		default:
            //get corresponding ascii for letters and numbers
            //invalid scan code, break
			//temp handler in checkpoint1
			if (scan_code >= SCAN_CODE_PRESS && !numl) break;
			//if shift and caps are pressed
			if (shrf && caps) {
				ascii = scan_code_table_shift_caps[scan_code];
			}  
			//only caps is pressed
            else if (caps) {
				ascii = scan_code_table_caps[scan_code];
			}
			//only srf is pressed
			else if (shrf) {
				ascii = scan_code_table_shift[scan_code];
			} 
			//Number lock is unlocked
			else if (numl) {
				ascii = scan_code_table_keypad[scan_code-KEYPAD_MASK];
			}
			//no special keys are pressed
            else {
				ascii = scan_code_table[scan_code];
			}
			//output
            putc(ascii);
			break;
	}

    //end of interrupt
	send_eoi(KEY_IRQ_NUM);
	//end of critical section
	sti();
}

