boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_linkage.o: interrupt_linkage.S interrupt_linkage.h
syscall_linkage.o: syscall_linkage.S syscall_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
command_history.o: command_history.c command_history.h types.h terminal.h \
  lib.h paging.h scheduler.h x86_desc.h
filesys.o: filesys.c filesys.h types.h syscall.h terminal.h rtc.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h interrupt_linkage.h \
  keyboard.h rtc.h syscall_linkage.h syscall.h terminal.h filesys.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h paging.h rtc.h keyboard.h idt.h filesys.h syscall.h terminal.h \
  scheduler.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h \
  command_history.h tab.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h scheduler.h paging.h \
  x86_desc.h
paging.o: paging.c paging.h types.h terminal.h
rtc.o: rtc.c i8259.h types.h lib.h rtc.h scheduler.h paging.h terminal.h \
  x86_desc.h time.h
scheduler.o: scheduler.c scheduler.h lib.h types.h paging.h terminal.h \
  x86_desc.h syscall.h filesys.h rtc.h i8259.h
speaker.o: speaker.c lib.h types.h scheduler.h paging.h terminal.h \
  x86_desc.h speaker.h
syscall.o: syscall.c syscall.h types.h terminal.h filesys.h rtc.h \
  x86_desc.h paging.h lib.h scheduler.h
tab.o: tab.c tab.h types.h lib.h scheduler.h paging.h terminal.h \
  x86_desc.h command_history.h
terminal.o: terminal.c terminal.h types.h lib.h keyboard.h paging.h \
  scheduler.h x86_desc.h command_history.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h terminal.h \
  filesys.h syscall.h
time.o: time.c time.h types.h rtc.h lib.h terminal.h
